# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chat_Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chat_Practice

  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'

end
